-- scripts/safe-space.luau
-- 15/09/2024
-- PWF2K

setfenv(1, {})


-- This is a safe-space, directly between the `setfenv`
-- and the `Update = nil`. It ensures whatever happens
-- within this script, stays within it.

-- No Standard Library. No `print`, `warn`, `error`s or `assert`s.
-- No dataypes. No `GameObject.new` or `Vector3`s.
-- The `Update = nil` ensures this Script is run only once
-- and ignored forever after.
-- Just data, and your thoughts.

-- Use it wisely.

-- I'm going to use it right now for my own reasons first though.
-- "Gave up. Gave in. Ending it all" (in "src/decl/gameobject/Example.cpp") is a FUCKING reference to a SHITTY thought I had
-- when watching the two new Helluva Boss episodes where I was D*MN near the brink of
-- insanity wondering why the FUCK Blit doesn't just FUCKING. Kill HIMSELF.
-- Like why does this Piece Of SHIT keep trying to talk to someone he FUCKED over.
-- Like dude?? Just kill yourself?? Or give up at the very least??
-- Like Stolass he over u kys mate
-- Also why the FUCK does Stolas look over to Blito when that new FUCKER
-- asks him to dance like he's asking for permission?? Grow some BALLS
-- cloaca ASS
-- I wrote it down in this 2 FUCKING MB text file I have as:
-- "Give up. Give in. End it all. Kill yourself."
-- FUCK SHIT PISS


Update = nil