-- Preferences.luau, 29/05/2026

return {
    Version = 1,
    AutoLaunchCodeEditorOnProjectOpen = false,
    ClearOutputOnProjectOpen = true,
    ClearOutputOnPlaytest = true,
    CodeEditorPath = "",
    ClosingProjectSaveRequiresConfirmation = false,
    AutosaveInterval = 5,
    KeepGizmoInView = false,
    InvertTabButtonLitColors = false,
    DevToolsOpen = { "Explorer", "Properties", "Scripts" },
    ToolsOpen = { BottomBar = true, Output = true },
    AutoReimportModels = true,
    GitIntegration = true,
    ProjectsDirectory = "@home/Documents/Phoenix Projects",
    ScriptAllowedExecutionTime = 10,
    CancelPlaytestWhenScriptTimesOut = true,
    Theme = "Dark",
    DebuggerEnabled = false,
}
